### ISSUE TITLE
Xcode 13 Beta3 - WVStack compile error

### ISSUE THREAD

**Issue by mk-conn** [diegolavalledev/swiftuilib-wrap-stack#4]
Just testing Xcode Beta and stumbled across this comile error:

```
wrap-stack/src/WVStack.swift:64:34: error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
  static var previews: some View {
```

**Comment by diegolavalledev** [comment]
Thanks I'm yet to try Xcode 13. If it's preview-related I guess it can be safely commented out. If it's a more serious issue, it might be an opportunity to include conditional code for iOS 14 and 15 that leverages the built-in lazy grids.

**Comment by samdeanpinknews** [comment]
Hi - I've created a PR to fix this here: #5 - definitely works on Xcode 14.3.1, and (as far as I know) there isn't anything too clever in there so should be backwards compatible.
